[package]
name = "summoner_sequencer"
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
summoner_core = { path = "../summoner_core" }
summoner_project = { path = "../summoner_project" }
summoner_harmony = { path = "../summoner_harmony" }
serde = { workspace = true }
