[package]
name = "summoner_gui"
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
summoner_core = { path = "../summoner_core" }
summoner_project = { path = "../summoner_project" }
summoner_harmony = { path = "../summoner_harmony" }
summoner_sequencer = { path = "../summoner_sequencer" }
summoner_dsp = { path = "../summoner_dsp" }
hound = "3.5"
serde = { workspace = true, features = ["derive"] }
toml = { workspace = true }

[dependencies.egui]
version = "0.28"
optional = true

[dependencies.eframe]
version = "0.28"
optional = true

[dependencies.rfd]
version = "0.14"
optional = true

[features]
default = []
gui = ["egui", "eframe", "rfd"]

