// Summoner - Deterministic, Headless-First DAW
// Copyright (C) 2026 nilsanderselde
// AGPLv3 License

//! Production-Grade Factory Preset & Soundbank Engine.
//! Provides curated out-of-the-box presets spanning Physical Modeling, General MIDI,
//! Chiptune/Tracker, Microtonal Harmony, Modern Synths, Studio FX, and Demo Song Templates.

use serde::{Deserialize, Serialize};

#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub enum FactoryPresetCategory {
    PhysicalModeling,
    GeneralMidi,
    ChiptuneTracker,
    MicrotonalHarmony,
    ModernSynth,
    StudioFx,
    DrumsPercussion,
}

impl FactoryPresetCategory {
    pub fn name(&self) -> &'static str {
        match self {
            Self::PhysicalModeling => "Physical Modeling",
            Self::GeneralMidi => "General MIDI",
            Self::ChiptuneTracker => "Chiptune & Tracker",
            Self::MicrotonalHarmony => "Microtonal & Harmony",
            Self::ModernSynth => "Modern Synth & Lo-Fi",
            Self::StudioFx => "Studio FX & Mastering",
            Self::DrumsPercussion => "Drums & Percussion",
        }
    }

    pub fn icon(&self) -> &'static str {
        match self {
            Self::PhysicalModeling => "🎻",
            Self::GeneralMidi => "🎹",
            Self::ChiptuneTracker => "👾",
            Self::MicrotonalHarmony => "✨",
            Self::ModernSynth => "⚡",
            Self::StudioFx => "🎛",
            Self::DrumsPercussion => "🥁",
        }
    }

    pub fn color_rgb(&self) -> (u8, u8, u8) {
        match self {
            Self::PhysicalModeling => (234, 179, 8),    // Amber / Gold
            Self::GeneralMidi => (56, 189, 248),        // Sky Blue
            Self::ChiptuneTracker => (239, 68, 68),     // Bright Red
            Self::MicrotonalHarmony => (168, 85, 247),  // Purple / Violet
            Self::ModernSynth => (236, 72, 153),        // Pink / Magenta
            Self::StudioFx => (16, 185, 129),           // Emerald Green
            Self::DrumsPercussion => (249, 115, 22),    // Orange
        }
    }
}

#[derive(Debug, Clone, Serialize)]
pub struct FactoryPreset {
    pub id: &'static str,
    pub name: &'static str,
    pub category: FactoryPresetCategory,
    pub target_node_kind: &'static str,
    pub description: &'static str,
    pub tags: &'static [&'static str],
    pub macro_tone: f32,
    pub macro_space: f32,
    pub macro_punch: f32,
    pub macro_character: f32,
    pub params: &'static [(&'static str, f32)],
    pub tuning_edo: Option<u16>,
    pub sample_preview_note: u8,
}

#[derive(Debug, Clone, Serialize)]
pub struct DemoTrackData {
    pub id: usize,
    pub name: &'static str,
    pub color_rgb: [u8; 3],
    pub is_audio: bool,
    pub gain: f32,
    pub pan: f32,
    pub preset_id: &'static str,
    pub clip_start_beat: f64,
    pub clip_length_beats: f64,
    pub notes: &'static [(u8, f64, f64, f32)], // (pitch_idx, start_beat, length_beats, velocity)
}

#[derive(Debug, Clone, Serialize)]
pub struct FactoryDemoTemplate {
    pub id: &'static str,
    pub title: &'static str,
    pub description: &'static str,
    pub bpm: f64,
    pub key_signature: &'static str,
    pub time_signature: &'static str,
    pub tuning_name: &'static str,
    pub tuning_edo: Option<u16>,
    pub tracks: &'static [DemoTrackData],
}

pub static FACTORY_PRESETS: &[FactoryPreset] = &[
    // --- 1. Physical Modeling (12 Presets) ---
    FactoryPreset {
        id: "steinway_grand_piano",
        name: "Steinway Concert Grand Piano",
        category: FactoryPresetCategory::PhysicalModeling,
        target_node_kind: "GrandPianoModel",
        description: "Imperial 9-foot concert grand piano with 3-string unison coupling and resonant Sitka spruce soundboard.",
        tags: &["piano", "acoustic", "keys", "steinway", "physical_model"],
        macro_tone: 0.72,
        macro_space: 0.40,
        macro_punch: 0.65,
        macro_character: 0.50,
        params: &[
            ("felt_hardness", 0.65),
            ("string_damping", 0.35),
            ("soundboard_resonance", 0.82),
            ("duplex_scale", 0.50),
            ("escapement_velocity", 0.78),
            ("hammer_width", 0.40),
            ("strike_position", 0.12),
        ],
        tuning_edo: None,
        sample_preview_note: 60,
    },
    FactoryPreset {
        id: "shakuhachi_flute",
        name: "Japanese Bamboo Shakuhachi",
        category: FactoryPresetCategory::PhysicalModeling,
        target_node_kind: "ShakuhachiModel",
        description: "End-blown traditional Japanese bamboo flute with dynamic meri/kari embouchure pitch bend and murai-iki breath bursts.",
        tags: &["woodwind", "flute", "bamboo", "japanese", "breath", "physical_model"],
        macro_tone: 0.60,
        macro_space: 0.55,
        macro_punch: 0.45,
        macro_character: 0.70,
        params: &[
            ("breath_pressure", 0.72),
            ("meri_kari_angle", 0.45),
            ("jet_length", 0.58),
            ("embouchure_leak", 0.30),
            ("tube_damping", 0.25),
            ("breath_noise", 0.45),
        ],
        tuning_edo: None,
        sample_preview_note: 62,
    },
    FactoryPreset {
        id: "ravi_sitar",
        name: "Hindustani Ravi Shankar Sitar",
        category: FactoryPresetCategory::PhysicalModeling,
        target_node_kind: "JawariBridge",
        description: "18-string Hindustani classical sitar with wide curved bone Jawari bridge buzz, chikari drones, and meend pulling.",
        tags: &["sitar", "indian", "plucked", "jawari", "drone", "physical_model"],
        macro_tone: 0.75,
        macro_space: 0.60,
        macro_punch: 0.50,
        macro_character: 0.80,
        params: &[
            ("jawari_curvature", 0.85),
            ("chikari_resonance", 0.75),
            ("meend_tension", 0.60),
            ("gourd_body_depth", 0.80),
            ("sympathetic_bleed", 0.65),
            ("pluck_hardness", 0.70),
        ],
        tuning_edo: None,
        sample_preview_note: 57,
    },
    FactoryPreset {
        id: "stradivarius_cello",
        name: "Cremona Stradivarius Bowed Cello",
        category: FactoryPresetCategory::PhysicalModeling,
        target_node_kind: "BowedStringModel",
        description: "Solo concert cello with non-linear stick-slip rosin friction, bow tilt dynamics, and spruce body air resonance.",
        tags: &["cello", "bowed", "strings", "solo", "rosin", "physical_model"],
        macro_tone: 0.65,
        macro_space: 0.45,
        macro_punch: 0.55,
        macro_character: 0.60,
        params: &[
            ("bow_velocity", 0.68),
            ("bow_force", 0.55),
            ("bow_position", 0.22),
            ("rosin_friction", 0.70),
            ("body_resonance", 0.85),
            ("bridge_bleed", 0.40),
        ],
        tuning_edo: None,
        sample_preview_note: 48,
    },
    FactoryPreset {
        id: "hammond_b3_organ",
        name: "Hammond B3 Tonewheel Organ",
        category: FactoryPresetCategory::PhysicalModeling,
        target_node_kind: "TonewheelOrganNode",
        description: "91-wheel vintage electromechanical tonewheel organ with full gospel 888000000 drawbars and 2-speed Leslie rotor.",
        tags: &["organ", "tonewheel", "hammond", "leslie", "drawbars", "keys"],
        macro_tone: 0.80,
        macro_space: 0.35,
        macro_punch: 0.70,
        macro_character: 0.65,
        params: &[
            ("drawbar_16", 0.90),
            ("drawbar_8", 1.00),
            ("drawbar_4", 0.80),
            ("drawbar_2", 0.70),
            ("key_click", 0.65),
            ("scanner_vibrato", 0.50),
            ("drive", 0.45),
        ],
        tuning_edo: None,
        sample_preview_note: 60,
    },
    FactoryPreset {
        id: "hohner_clavinet_d6",
        name: "Hohner D6 Funk Clavinet",
        category: FactoryPresetCategory::PhysicalModeling,
        target_node_kind: "ClavinetVoice",
        description: "Electromechanical funk clavinet with dual magnetic pickups, rubber tangent strike action, and brilliant tone filters.",
        tags: &["clavinet", "funk", "keys", "electric", "tangent", "physical_model"],
        macro_tone: 0.85,
        macro_space: 0.20,
        macro_punch: 0.80,
        macro_character: 0.70,
        params: &[
            ("tangent_force", 0.88),
            ("pickup_phase", 0.50),
            ("damp_release", 0.20),
            ("tone_treble", 0.80),
            ("brilliant_filter", 0.75),
            ("whammy_mod", 0.00),
        ],
        tuning_edo: None,
        sample_preview_note: 58,
    },
    FactoryPreset {
        id: "rhodes_mark_1",
        name: "Rhodes Mark I Stage Electric Piano",
        category: FactoryPresetCategory::PhysicalModeling,
        target_node_kind: "ElectricPianoModel",
        description: "Tine-based electromechanical electric piano with inductive coil pickups, neoprene hammer tips, and lush harmonic bark.",
        tags: &["rhodes", "electric_piano", "tine", "vintage", "keys", "physical_model"],
        macro_tone: 0.68,
        macro_space: 0.40,
        macro_punch: 0.60,
        macro_character: 0.55,
        params: &[
            ("tine_stiffness", 0.60),
            ("pickup_distance", 0.35),
            ("hammer_hardness", 0.70),
            ("damper_decay", 0.55),
            ("bark_saturation", 0.65),
            ("tremolo_rate", 0.45),
        ],
        tuning_edo: None,
        sample_preview_note: 60,
    },
    FactoryPreset {
        id: "baroque_pipe_organ",
        name: "Baroque Cathedral Pipe Organ",
        category: FactoryPresetCategory::PhysicalModeling,
        target_node_kind: "PipeOrganModel",
        description: "Cathedral 64-foot mechanical tracker organ with windchest reservoir, plenum mixture ranks, and reverberant hall bloom.",
        tags: &["pipe_organ", "cathedral", "sacred", "baroque", "wind", "physical_model"],
        macro_tone: 0.70,
        macro_space: 0.85,
        macro_punch: 0.50,
        macro_character: 0.75,
        params: &[
            ("windchest_pressure", 0.78),
            ("tracker_action", 0.60),
            ("plenum_ranks", 0.85),
            ("room_dispersion", 0.90),
            ("pipe_chiff", 0.45),
            ("mixture_octave", 0.70),
        ],
        tuning_edo: None,
        sample_preview_note: 48,
    },
    FactoryPreset {
        id: "rosewood_marimba",
        name: "Rosewood Concert Marimba",
        category: FactoryPresetCategory::PhysicalModeling,
        target_node_kind: "StruckIdiophoneResonator",
        description: "Honduran rosewood concert marimba bars coupled to tuned brass resonator tubes with soft yarn mallet strikes.",
        tags: &["marimba", "mallet", "percussion", "wooden", "rosewood", "physical_model"],
        macro_tone: 0.65,
        macro_space: 0.45,
        macro_punch: 0.75,
        macro_character: 0.50,
        params: &[
            ("mallet_hardness", 0.55),
            ("bar_tuning", 0.80),
            ("resonator_depth", 0.75),
            ("decay_rate", 0.65),
            ("acoustic_radiation", 0.70),
            ("stereo_width", 0.80),
        ],
        tuning_edo: None,
        sample_preview_note: 64,
    },
    FactoryPreset {
        id: "concert_lever_harp",
        name: "Celtic Concert Lever Harp",
        category: FactoryPresetCategory::PhysicalModeling,
        target_node_kind: "PlectrumBus",
        description: "34-string Celtic concert nylon harp with spruce soundbox resonance and sympathetic string ring.",
        tags: &["harp", "celtic", "acoustic", "strings", "plucked", "physical_model"],
        macro_tone: 0.70,
        macro_space: 0.60,
        macro_punch: 0.50,
        macro_character: 0.60,
        params: &[
            ("pluck_force", 0.60),
            ("string_tension", 0.70),
            ("soundbox_volume", 0.80),
            ("sympathetic_resonance", 0.65),
            ("damping_decay", 0.50),
            ("lever_sharp", 0.00),
        ],
        tuning_edo: None,
        sample_preview_note: 65,
    },
    FactoryPreset {
        id: "bourbonnais_hurdy_gurdy",
        name: "Bourbonnais Hurdy-Gurdy",
        category: FactoryPresetCategory::PhysicalModeling,
        target_node_kind: "HurdyGurdySoundboxBody",
        description: "Traditional French folk vielle à roue with continuous rosin wheel excitation, buzzing chien bridge, and octave drones.",
        tags: &["hurdy_gurdy", "folk", "drone", "chien", "friction", "physical_model"],
        macro_tone: 0.72,
        macro_space: 0.40,
        macro_punch: 0.65,
        macro_character: 0.85,
        params: &[
            ("wheel_speed", 0.70),
            ("rosin_cohesion", 0.65),
            ("chien_buzz", 0.55),
            ("drone_amplitude", 0.80),
            ("soundbox_bleed", 0.75),
            ("crank_accent", 0.60),
        ],
        tuning_edo: None,
        sample_preview_note: 55,
    },
    FactoryPreset {
        id: "glass_armonica",
        name: "Benjamin Franklin Glass Armonica",
        category: FactoryPresetCategory::PhysicalModeling,
        target_node_kind: "ArmonicaChassisResonator",
        description: "Rotational nested quartz lead-crystal singing bowls with wet-finger friction contact and ethereal shimmering overtones.",
        tags: &["glass_armonica", "crystal", "ethereal", "singing_bowls", "friction", "physical_model"],
        macro_tone: 0.85,
        macro_space: 0.80,
        macro_punch: 0.30,
        macro_character: 0.90,
        params: &[
            ("bowl_rim_friction", 0.65),
            ("water_depth", 0.40),
            ("crystal_damping", 0.15),
            ("orbital_velocity", 0.50),
            ("celestial_shimmer", 0.85),
            ("rotational_spin", 0.60),
        ],
        tuning_edo: None,
        sample_preview_note: 72,
    },

    // --- 2. General MIDI Soundbank (10 Presets, WISHLIST.md) ---
    FactoryPreset {
        id: "gm_grand_piano",
        name: "General MIDI Acoustic Grand Piano",
        category: FactoryPresetCategory::GeneralMidi,
        target_node_kind: "GrandPianoModel",
        description: "General MIDI Patch 001: Standard acoustic concert grand piano soundbank voicing.",
        tags: &["gm", "piano", "acoustic", "keys", "soundbank", "gm001"],
        macro_tone: 0.70,
        macro_space: 0.35,
        macro_punch: 0.60,
        macro_character: 0.50,
        params: &[
            ("hammer_velocity", 0.80),
            ("damper_pedal", 0.0),
            ("brilliance", 0.70),
            ("soundboard_mix", 0.60),
            ("stereo_spread", 0.80),
        ],
        tuning_edo: None,
        sample_preview_note: 60,
    },
    FactoryPreset {
        id: "gm_electric_piano",
        name: "General MIDI Electric Piano 1 (Rhodes)",
        category: FactoryPresetCategory::GeneralMidi,
        target_node_kind: "ElectricPianoModel",
        description: "General MIDI Patch 005: Classic vintage electric piano with bell tine clarity.",
        tags: &["gm", "electric_piano", "rhodes", "keys", "soundbank", "gm005"],
        macro_tone: 0.65,
        macro_space: 0.40,
        macro_punch: 0.55,
        macro_character: 0.60,
        params: &[
            ("tine_resonance", 0.75),
            ("pickup_drive", 0.60),
            ("tremolo_depth", 0.30),
            ("bell_character", 0.65),
            ("velocity_dynamics", 0.85),
        ],
        tuning_edo: None,
        sample_preview_note: 60,
    },
    FactoryPreset {
        id: "gm_drawbar_organ",
        name: "General MIDI Drawbar Organ",
        category: FactoryPresetCategory::GeneralMidi,
        target_node_kind: "TonewheelOrganNode",
        description: "General MIDI Patch 017: Vintage jazz drawbar organ with fast rotary chorus.",
        tags: &["gm", "organ", "drawbar", "keys", "soundbank", "gm017"],
        macro_tone: 0.75,
        macro_space: 0.30,
        macro_punch: 0.65,
        macro_character: 0.55,
        params: &[
            ("drawbar_sub", 0.80),
            ("drawbar_fund", 1.00),
            ("drawbar_fifth", 0.60),
            ("rotor_speed", 0.50),
            ("overdrive", 0.25),
        ],
        tuning_edo: None,
        sample_preview_note: 60,
    },
    FactoryPreset {
        id: "gm_church_organ",
        name: "General MIDI Church Pipe Organ",
        category: FactoryPresetCategory::GeneralMidi,
        target_node_kind: "PipeOrganModel",
        description: "General MIDI Patch 019: Traditional church sanctuary pipe organ with full ranks.",
        tags: &["gm", "pipe_organ", "church", "soundbank", "gm019"],
        macro_tone: 0.68,
        macro_space: 0.80,
        macro_punch: 0.50,
        macro_character: 0.70,
        params: &[
            ("tracker_chiff", 0.50),
            ("wind_stability", 0.85),
            ("mixture_ranks", 0.70),
            ("acoustic_space", 0.80),
            ("reed_presence", 0.40),
        ],
        tuning_edo: None,
        sample_preview_note: 48,
    },
    FactoryPreset {
        id: "gm_nylon_guitar",
        name: "General MIDI Nylon String Guitar",
        category: FactoryPresetCategory::GeneralMidi,
        target_node_kind: "PluckSynth",
        description: "General MIDI Patch 025: Classical acoustic Spanish guitar with warm nylon fingerpicking.",
        tags: &["gm", "guitar", "nylon", "acoustic", "soundbank", "gm025"],
        macro_tone: 0.60,
        macro_space: 0.45,
        macro_punch: 0.50,
        macro_character: 0.50,
        params: &[
            ("pluck_hardness", 0.50),
            ("string_tension", 0.65),
            ("body_size", 0.60),
            ("sustain_decay", 0.45),
            ("fret_noise", 0.20),
        ],
        tuning_edo: None,
        sample_preview_note: 52,
    },
    FactoryPreset {
        id: "gm_rock_guitar",
        name: "General MIDI Overdriven Rock Guitar",
        category: FactoryPresetCategory::GeneralMidi,
        target_node_kind: "DistortionNode",
        description: "General MIDI Patch 030: Searing electric lead guitar through an overdriven tube amp.",
        tags: &["gm", "guitar", "overdrive", "rock", "distortion", "soundbank", "gm030"],
        macro_tone: 0.80,
        macro_space: 0.35,
        macro_punch: 0.85,
        macro_character: 0.75,
        params: &[
            ("drive", 0.85),
            ("tone", 0.65),
            ("bass_cut", 0.40),
            ("cabinet_sim", 0.80),
            ("feedback_amount", 0.30),
        ],
        tuning_edo: None,
        sample_preview_note: 57,
    },
    FactoryPreset {
        id: "gm_acoustic_bass",
        name: "General MIDI Acoustic Bass",
        category: FactoryPresetCategory::GeneralMidi,
        target_node_kind: "BowedStringModel",
        description: "General MIDI Patch 033: Upright wooden acoustic double bass plucked pizzicato.",
        tags: &["gm", "bass", "acoustic_bass", "upright", "soundbank", "gm033"],
        macro_tone: 0.50,
        macro_space: 0.25,
        macro_punch: 0.80,
        macro_character: 0.55,
        params: &[
            ("finger_pluck", 0.75),
            ("wooden_body", 0.80),
            ("low_end_bloom", 0.85),
            ("transient_snap", 0.60),
            ("mwah_decay", 0.50),
        ],
        tuning_edo: None,
        sample_preview_note: 36,
    },
    FactoryPreset {
        id: "gm_synth_brass",
        name: "General MIDI Synth Brass 1",
        category: FactoryPresetCategory::GeneralMidi,
        target_node_kind: "WaveguideBrassModel",
        description: "General MIDI Patch 062: Classic 80s analog synthesizer brass section with sweeping filter punch.",
        tags: &["gm", "synth_brass", "80s", "brass", "soundbank", "gm062"],
        macro_tone: 0.75,
        macro_space: 0.40,
        macro_punch: 0.75,
        macro_character: 0.65,
        params: &[
            ("filter_cutoff", 0.65),
            ("filter_env_amt", 0.75),
            ("attack_time", 0.20),
            ("decay_time", 0.60),
            ("unison_detune", 0.40),
        ],
        tuning_edo: None,
        sample_preview_note: 60,
    },
    FactoryPreset {
        id: "gm_shakuhachi",
        name: "General MIDI Shakuhachi Flute",
        category: FactoryPresetCategory::GeneralMidi,
        target_node_kind: "ShakuhachiModel",
        description: "General MIDI Patch 073: Ethnic Japanese bamboo flute with traditional breath noise.",
        tags: &["gm", "shakuhachi", "flute", "world", "soundbank", "gm073"],
        macro_tone: 0.65,
        macro_space: 0.50,
        macro_punch: 0.40,
        macro_character: 0.70,
        params: &[
            ("breath_noise", 0.60),
            ("overblow_threshold", 0.40),
            ("vibrato_speed", 0.50),
            ("vibrato_depth", 0.35),
            ("air_resonance", 0.70),
        ],
        tuning_edo: None,
        sample_preview_note: 62,
    },
    FactoryPreset {
        id: "gm_standard_drums",
        name: "General MIDI Standard Drum Kit 1",
        category: FactoryPresetCategory::GeneralMidi,
        target_node_kind: "DrumMachineDevice",
        description: "General MIDI Patch 128: Standard multi-velocity acoustic studio drum kit with kick, snare, toms, and cymbals.",
        tags: &["gm", "drums", "drum_kit", "percussion", "soundbank", "gm128"],
        macro_tone: 0.70,
        macro_space: 0.30,
        macro_punch: 0.85,
        macro_character: 0.50,
        params: &[
            ("kick_punch", 0.90),
            ("snare_snap", 0.85),
            ("hihat_sizzle", 0.75),
            ("tom_decay", 0.65),
            ("room_bleed", 0.40),
        ],
        tuning_edo: None,
        sample_preview_note: 36,
    },

    // --- 3. Chiptune & Tracker (5 Presets, WISHLIST.md) ---
    FactoryPreset {
        id: "nes_pulse_lead",
        name: "Chiptune 8-Bit NES Pulse Lead",
        category: FactoryPresetCategory::ChiptuneTracker,
        target_node_kind: "OscPulse",
        description: "Nintendo Entertainment System 2A03 dual pulse wave lead with variable duty cycle sweep.",
        tags: &["chiptune", "8bit", "nes", "pulse", "retro", "tracker"],
        macro_tone: 0.85,
        macro_space: 0.15,
        macro_punch: 0.80,
        macro_character: 0.75,
        params: &[
            ("duty_cycle", 0.50),
            ("sweep_rate", 0.30),
            ("vibrato_depth", 0.25),
            ("volume_env", 0.90),
            ("bit_crush", 0.80),
        ],
        tuning_edo: None,
        sample_preview_note: 60,
    },
    FactoryPreset {
        id: "gameboy_triangle_bass",
        name: "Chiptune 8-Bit GameBoy Triangle Bass",
        category: FactoryPresetCategory::ChiptuneTracker,
        target_node_kind: "OscTriangle",
        description: "GameBoy DMG 4-bit custom waveform stepped triangle sub-bass with lo-fi punch.",
        tags: &["chiptune", "8bit", "gameboy", "triangle", "bass", "retro"],
        macro_tone: 0.40,
        macro_space: 0.10,
        macro_punch: 0.90,
        macro_character: 0.50,
        params: &[
            ("drive", 0.20),
            ("octave_shift", 0.00),
            ("filter_cutoff", 0.95),
            ("step_quantize", 0.85),
            ("sub_level", 0.70),
        ],
        tuning_edo: None,
        sample_preview_note: 36,
    },
    FactoryPreset {
        id: "sid_6581_arp",
        name: "Commodore 64 SID 6581 Arpeggiator",
        category: FactoryPresetCategory::ChiptuneTracker,
        target_node_kind: "TrackerStepConfig",
        description: "MOS 6581 SID chip analog multimode filter sweep with rapid 50Hz hardware arpeggiator.",
        tags: &["chiptune", "sid", "c64", "commodore", "arp", "tracker"],
        macro_tone: 0.80,
        macro_space: 0.25,
        macro_punch: 0.80,
        macro_character: 0.85,
        params: &[
            ("arp_speed", 0.85),
            ("ring_mod", 0.60),
            ("sync_osc", 0.50),
            ("filter_sweep", 0.70),
            ("wave_morph", 0.40),
        ],
        tuning_edo: None,
        sample_preview_note: 60,
    },
    FactoryPreset {
        id: "fasttracker_arp_slicer",
        name: "Chiptune FastTracker II Arp Arpeggio",
        category: FactoryPresetCategory::ChiptuneTracker,
        target_node_kind: "TrackerStepConfig",
        description: "Amiga and PC tracker era multi-octave 0xy arpeggiator chord emulation at 125 BPM.",
        tags: &["tracker", "fasttracker", "amiga", "mod", "xm", "chiptune"],
        macro_tone: 0.75,
        macro_space: 0.20,
        macro_punch: 0.70,
        macro_character: 0.65,
        params: &[
            ("tick_tempo", 0.90),
            ("glide_speed", 0.35),
            ("sample_offset", 0.00),
            ("volume_slide", 0.60),
            ("retrigger_count", 0.50),
        ],
        tuning_edo: None,
        sample_preview_note: 60,
    },
    FactoryPreset {
        id: "chiptune_noise_drums",
        name: "Chiptune Noise Snare & Hi-Hat",
        category: FactoryPresetCategory::ChiptuneTracker,
        target_node_kind: "NoiseGen",
        description: "Linear-feedback shift register (LFSR) 1-bit pseudorandom noise percussion generator.",
        tags: &["chiptune", "noise", "percussion", "drums", "snare", "hihat"],
        macro_tone: 0.85,
        macro_space: 0.15,
        macro_punch: 0.90,
        macro_character: 0.60,
        params: &[
            ("noise_type", 0.70),
            ("envelope_decay", 0.25),
            ("lfsr_period", 0.60),
            ("filter_resonance", 0.40),
            ("click_transient", 0.80),
        ],
        tuning_edo: None,
        sample_preview_note: 42,
    },

    // --- 4. Microtonal & Harmony (5 Presets) ---
    FactoryPreset {
        id: "19_edo_neutral_pad",
        name: "Microtonal 19-EDO Neutral Third Pad",
        category: FactoryPresetCategory::MicrotonalHarmony,
        target_node_kind: "EdoTuning",
        description: "19 Equal Divisions of the Octave featuring perfectly balanced neutral thirds and warm acoustic beating.",
        tags: &["microtonal", "19_edo", "pad", "harmony", "neutral_third", "tuning"],
        macro_tone: 0.60,
        macro_space: 0.65,
        macro_punch: 0.40,
        macro_character: 0.80,
        params: &[
            ("sub_octave", 0.40),
            ("shimmer_detune", 0.30),
            ("chorus_width", 0.80),
            ("filter_cutoff", 0.60),
            ("long_decay", 0.85),
        ],
        tuning_edo: Some(19),
        sample_preview_note: 60,
    },
    FactoryPreset {
        id: "31_edo_justness_lead",
        name: "Microtonal 31-EDO Extended Justness Lead",
        category: FactoryPresetCategory::MicrotonalHarmony,
        target_node_kind: "EdoTuning",
        description: "31 Equal Divisions of the Octave approximating quarter-comma meantone and pure septimal 7/4 harmonic consonances.",
        tags: &["microtonal", "31_edo", "lead", "septimal", "meantone", "tuning"],
        macro_tone: 0.75,
        macro_space: 0.45,
        macro_punch: 0.65,
        macro_character: 0.70,
        params: &[
            ("septimal_concord", 0.85),
            ("glide_slew", 0.20),
            ("vibrato_cents", 0.15),
            ("overtone_mix", 0.55),
            ("bright_presence", 0.70),
        ],
        tuning_edo: Some(31),
        sample_preview_note: 62,
    },
    FactoryPreset {
        id: "53_edo_makam_drone",
        name: "Microtonal 53-EDO Turkish Makam Drone",
        category: FactoryPresetCategory::MicrotonalHarmony,
        target_node_kind: "CadenceGraph",
        description: "53 Equal Divisions of the Octave providing exact Pythagorean and syntonic Holder commas for classical Turkish makams.",
        tags: &["microtonal", "53_edo", "makam", "drone", "turkish", "tuning"],
        macro_tone: 0.55,
        macro_space: 0.75,
        macro_punch: 0.35,
        macro_character: 0.90,
        params: &[
            ("comma_detune", 0.10),
            ("drone_swell", 0.80),
            ("harmonic_ratio", 0.75),
            ("acoustic_air", 0.60),
            ("maqam_cadence", 0.85),
        ],
        tuning_edo: Some(53),
        sample_preview_note: 55,
    },
    FactoryPreset {
        id: "bp_gamma_chime",
        name: "Bohlen-Pierce Non-Octave Tritave Chime",
        category: FactoryPresetCategory::MicrotonalHarmony,
        target_node_kind: "ConcordanceLattice",
        description: "Non-octave 3:1 tritave scale using odd harmonic ratios (3:5:7:9) and crystalline metallic resonance.",
        tags: &["microtonal", "bohlen_pierce", "non_octave", "tritave", "chime"],
        macro_tone: 0.80,
        macro_space: 0.70,
        macro_punch: 0.45,
        macro_character: 0.85,
        params: &[
            ("tritave_ratio", 0.90),
            ("odd_harmonic_mix", 0.85),
            ("metal_transient", 0.70),
            ("space_reverb", 0.80),
            ("crystalline_damping", 0.40),
        ],
        tuning_edo: None,
        sample_preview_note: 67,
    },
    FactoryPreset {
        id: "22_edo_porcupine_bass",
        name: "Microtonal 22-EDO Porcupine Bass",
        category: FactoryPresetCategory::MicrotonalHarmony,
        target_node_kind: "EdoTuning",
        description: "22 Equal Divisions of the Octave porcupine temperament sub-bass with punchy attack.",
        tags: &["microtonal", "22_edo", "bass", "porcupine", "tuning"],
        macro_tone: 0.50,
        macro_space: 0.20,
        macro_punch: 0.90,
        macro_character: 0.60,
        params: &[
            ("sub_drive", 0.80),
            ("filter_damping", 0.50),
            ("punch_attack", 0.90),
            ("mono_glide", 0.30),
            ("low_resonance", 0.65),
        ],
        tuning_edo: Some(22),
        sample_preview_note: 36,
    },

    // --- 5. Modern Synth & Lo-Fi (5 Presets) ---
    FactoryPreset {
        id: "aether_warm_pad",
        name: "Aether Warm Pad",
        category: FactoryPresetCategory::ModernSynth,
        target_node_kind: "AtmosphericPadSynth",
        description: "Lush multi-oscillator polyphonic ambient pad with warm analog filter drift and chorus.",
        tags: &["synth", "pad", "analog", "warm", "ambient", "aether"],
        macro_tone: 0.65,
        macro_space: 0.60,
        macro_punch: 0.40,
        macro_character: 0.55,
        params: &[
            ("cutoff", 0.55),
            ("resonance", 0.35),
            ("chorus_depth", 0.70),
            ("attack_time", 0.65),
            ("release_time", 0.80),
        ],
        tuning_edo: None,
        sample_preview_note: 60,
    },
    FactoryPreset {
        id: "cyberpunk_808_sub",
        name: "808 Sub Kick",
        category: FactoryPresetCategory::ModernSynth,
        target_node_kind: "CyberpunkSubSynth",
        description: "Heavy distorted 808 sub-bass with tuned pitch envelope drop and saturated punch.",
        tags: &["bass", "808", "sub", "kick", "cyberpunk", "distortion"],
        macro_tone: 0.45,
        macro_space: 0.15,
        macro_punch: 0.95,
        macro_character: 0.70,
        params: &[
            ("pitch_drop", 0.85),
            ("sub_saturation", 0.75),
            ("click_punch", 0.90),
            ("boom_decay", 0.70),
            ("phase_align", 0.50),
        ],
        tuning_edo: None,
        sample_preview_note: 36,
    },
    FactoryPreset {
        id: "moog_ladder_lead",
        name: "Moog 4-Pole Ladder Self-Oscillation",
        category: FactoryPresetCategory::ModernSynth,
        target_node_kind: "LadderFilterBode",
        description: "Iconic 24dB/oct transistor ladder filter driven into non-linear tanh saturation and self-oscillation.",
        tags: &["moog", "ladder", "filter", "analog", "lead", "synth"],
        macro_tone: 0.75,
        macro_space: 0.35,
        macro_punch: 0.70,
        macro_character: 0.80,
        params: &[
            ("cutoff", 0.70),
            ("resonance", 0.92),
            ("drive", 0.65),
            ("key_tracking", 0.80),
            ("env_depth", 0.60),
        ],
        tuning_edo: None,
        sample_preview_note: 60,
    },
    FactoryPreset {
        id: "vowel_formant_morpher",
        name: "Kelly-Lochbaum Formant Vowel Kelly Acoustic Waveguide",
        category: FactoryPresetCategory::ModernSynth,
        target_node_kind: "VowelPreset",
        description: "Acoustic vocal tract reflection cylinder model smoothly interpolating between /i/, /a/, and /u/ formants.",
        tags: &["vowel", "formant", "vocal_tract", "morph", "synth"],
        macro_tone: 0.70,
        macro_space: 0.50,
        macro_punch: 0.50,
        macro_character: 0.85,
        params: &[
            ("formant_shift", 0.50),
            ("vowel_morph", 0.65),
            ("breathiness", 0.30),
            ("nasal_balance", 0.40),
            ("throat_width", 0.55),
        ],
        tuning_edo: None,
        sample_preview_note: 60,
    },
    FactoryPreset {
        id: "chaotic_lorenz_modulator",
        name: "Stochastic Chaos Modulation & Algorithmic Random Generator",
        category: FactoryPresetCategory::ModernSynth,
        target_node_kind: "LuaRandomEngine",
        description: "Lorenz non-linear strange attractor generating aperiodic, continuously evolving multi-axis control voltages.",
        tags: &["chaos", "lorenz", "modulator", "lfo", "algorithmic"],
        macro_tone: 0.55,
        macro_space: 0.40,
        macro_punch: 0.60,
        macro_character: 0.90,
        params: &[
            ("chaos_speed", 0.60),
            ("attractor_sigma", 0.75),
            ("rho_dimension", 0.85),
            ("modulation_matrix", 0.70),
            ("smoothing", 0.40),
        ],
        tuning_edo: None,
        sample_preview_note: 60,
    },

    // --- 6. Studio FX & Mastering (5 Presets) ---
    FactoryPreset {
        id: "tape_saturation_lead",
        name: "Vintage Tape Lead",
        category: FactoryPresetCategory::StudioFx,
        target_node_kind: "TapeSaturation",
        description: "Analog 15 IPS reel-to-reel magnetic tape machine saturation with head-bump bass and high-frequency soft clipping.",
        tags: &["tape", "saturation", "analog", "warmth", "studio_fx"],
        macro_tone: 0.70,
        macro_space: 0.30,
        macro_punch: 0.75,
        macro_character: 0.65,
        params: &[
            ("tape_speed_ips", 0.75),
            ("input_drive", 0.65),
            ("bias_hf", 0.50),
            ("wow_flutter", 0.30),
            ("head_bump", 0.60),
        ],
        tuning_edo: None,
        sample_preview_note: 60,
    },
    FactoryPreset {
        id: "emt140_plate_reverb",
        name: "Vintage EMT-140 Cold-Rolled Steel Suspension Reverb",
        category: FactoryPresetCategory::StudioFx,
        target_node_kind: "PlateTank",
        description: "Legendary 600-pound cold-rolled steel sheet mechanical plate reverb with continuous dispersion and high density.",
        tags: &["reverb", "plate", "emt140", "vintage", "space", "studio_fx"],
        macro_tone: 0.65,
        macro_space: 0.85,
        macro_punch: 0.30,
        macro_character: 0.70,
        params: &[
            ("decay_time_s", 0.70),
            ("damping_hf", 0.45),
            ("pre_delay_ms", 0.25),
            ("diffusion", 0.85),
            ("bass_filter", 0.40),
        ],
        tuning_edo: None,
        sample_preview_note: 60,
    },
    FactoryPreset {
        id: "master_true_peak_limiter",
        name: "Master Brickwall True-Peak Limiter",
        category: FactoryPresetCategory::StudioFx,
        target_node_kind: "MasterLimiter",
        description: "ITU-R BS.1770 true-peak inter-sample ceiling limiter with 4x polyphase oversampling and auto-release.",
        tags: &["limiter", "mastering", "true_peak", "itu", "dynamics", "studio_fx"],
        macro_tone: 0.50,
        macro_space: 0.10,
        macro_punch: 0.90,
        macro_character: 0.30,
        params: &[
            ("threshold_db", 0.80),
            ("ceiling_db", 0.95),
            ("release_ms", 0.40),
            ("lookahead_ms", 0.60),
            ("oversample_4x", 1.00),
        ],
        tuning_edo: None,
        sample_preview_note: 60,
    },
    FactoryPreset {
        id: "binaural_3d_spatializer",
        name: "Spherical Harmonic 3D Binaural HRTF Soundfield",
        category: FactoryPresetCategory::StudioFx,
        target_node_kind: "BinauralHrtfInterpolator",
        description: "Head-Related Transfer Function (HRTF) 360-degree azimuth and elevation binaural panner with Doppler shift.",
        tags: &["spatial", "hrtf", "binaural", "3d", "surround", "studio_fx"],
        macro_tone: 0.60,
        macro_space: 0.75,
        macro_punch: 0.40,
        macro_character: 0.80,
        params: &[
            ("azimuth_deg", 0.60),
            ("elevation_deg", 0.50),
            ("distance_m", 0.45),
            ("room_early_ref", 0.70),
            ("doppler_scale", 0.35),
        ],
        tuning_edo: None,
        sample_preview_note: 60,
    },
    FactoryPreset {
        id: "nam_tube_overdrive",
        name: "Neural High-Gain Amp Stack",
        category: FactoryPresetCategory::StudioFx,
        target_node_kind: "NamModelConfig",
        description: "Neural Amp Modeler WaveNet neural network emulation of a high-gain 100W valve tube amplifier stack.",
        tags: &["amp", "guitar", "neural", "wavenet", "tube", "distortion", "studio_fx"],
        macro_tone: 0.75,
        macro_space: 0.25,
        macro_punch: 0.90,
        macro_character: 0.75,
        params: &[
            ("gain_drive", 0.85),
            ("bass", 0.60),
            ("middle", 0.55),
            ("treble", 0.70),
            ("presence", 0.65),
        ],
        tuning_edo: None,
        sample_preview_note: 57,
    },

    // --- 7. Drums & Percussion (5 Presets) ---
    FactoryPreset {
        id: "studio_drum_kit",
        name: "Tactile 16-Pad Groove Machine",
        category: FactoryPresetCategory::DrumsPercussion,
        target_node_kind: "DrumMacroStrip",
        description: "Acoustic multi-mic recording session drum kit with discrete snare top/bottom and overhead phase alignment.",
        tags: &["drums", "acoustic", "groove", "kit", "percussion"],
        macro_tone: 0.70,
        macro_space: 0.35,
        macro_punch: 0.85,
        macro_character: 0.50,
        params: &[
            ("kick_vol", 0.90),
            ("snare_vol", 0.85),
            ("hihat_vol", 0.70),
            ("tom_vol", 0.75),
            ("overhead_vol", 0.80),
        ],
        tuning_edo: None,
        sample_preview_note: 36,
    },
    FactoryPreset {
        id: "orchestral_timpani",
        name: "Tuned Orchestral Timpani Membrane",
        category: FactoryPresetCategory::DrumsPercussion,
        target_node_kind: "PercussionMembrane",
        description: "2D circular Bessel membrane acoustic copper kettle timpani with pedal pitch tuning and felt mallet strike.",
        tags: &["timpani", "orchestral", "membrane", "percussion", "copper"],
        macro_tone: 0.55,
        macro_space: 0.60,
        macro_punch: 0.80,
        macro_character: 0.65,
        params: &[
            ("membrane_tension", 0.65),
            ("mallet_impact", 0.80),
            ("kettle_air_coupling", 0.85),
            ("pitch_bend", 0.50),
            ("damping", 0.40),
        ],
        tuning_edo: None,
        sample_preview_note: 41,
    },
    FactoryPreset {
        id: "concert_snare_rattle",
        name: "Concert Snare Drum Rattle",
        category: FactoryPresetCategory::DrumsPercussion,
        target_node_kind: "SnareRattleModel",
        description: "Dual-head 14-inch snare drum with coiled wire rattle impact non-linearities and wooden rim clicks.",
        tags: &["snare", "rattle", "percussion", "acoustic", "drums"],
        macro_tone: 0.75,
        macro_space: 0.30,
        macro_punch: 0.90,
        macro_character: 0.60,
        params: &[
            ("snare_wire_tension", 0.75),
            ("head_impact", 0.85),
            ("wire_buzz_decay", 0.60),
            ("acoustic_bleed", 0.50),
            ("shell_ring", 0.40),
        ],
        tuning_edo: None,
        sample_preview_note: 38,
    },
    FactoryPreset {
        id: "lofi_breakbeat_slice",
        name: "Lo-Fi Breakbeat",
        category: FactoryPresetCategory::DrumsPercussion,
        target_node_kind: "LoopSlicerNode",
        description: "Vintage funk breakbeat sliced at zero-crossings with 12-bit sampler crunch and pitch downshift.",
        tags: &["breakbeat", "lofi", "sampler", "drums", "slicer"],
        macro_tone: 0.60,
        macro_space: 0.20,
        macro_punch: 0.85,
        macro_character: 0.80,
        params: &[
            ("slice_sensitivity", 0.75),
            ("pitch_shift", 0.40),
            ("bit_depth_bits", 0.45),
            ("swing", 0.55),
            ("filter_env", 0.60),
        ],
        tuning_edo: None,
        sample_preview_note: 36,
    },
    FactoryPreset {
        id: "struck_bell_idiophone",
        name: "Concert Rosewood Marimba",
        category: FactoryPresetCategory::DrumsPercussion,
        target_node_kind: "IdiophoneResonator",
        description: "Struck wooden idiophone bar matrix with tuned resonator cavities and polyphonic mallet routing.",
        tags: &["marimba", "idiophone", "tuned", "percussion", "acoustic"],
        macro_tone: 0.70,
        macro_space: 0.50,
        macro_punch: 0.70,
        macro_character: 0.55,
        params: &[
            ("mallet_velocity", 0.75),
            ("tube_resonance", 0.80),
            ("timber_hardness", 0.60),
            ("stereo_spread", 0.85),
            ("room_wet", 0.45),
        ],
        tuning_edo: None,
        sample_preview_note: 60,
    },
];

// --- 5 Built-in Factory Demo Templates ---
pub static DEMO_SHOWCASE_TRACKS: &[DemoTrackData] = &[
    DemoTrackData {
        id: 1,
        name: "Steinway Grand Piano",
        color_rgb: [56, 189, 248], // Sky Blue
        is_audio: false,
        gain: 0.95,
        pan: -0.15,
        preset_id: "steinway_grand_piano",
        clip_start_beat: 0.0,
        clip_length_beats: 16.0,
        notes: &[
            (3, 0.0, 1.5, 0.90),
            (5, 2.0, 1.5, 0.80),
            (8, 4.0, 2.0, 0.85),
            (10, 6.0, 1.5, 0.75),
            (12, 8.0, 3.0, 0.95),
            (10, 11.5, 1.0, 0.70),
            (8, 13.0, 2.0, 0.85),
            (3, 15.0, 2.0, 1.00),
        ],
    },
    DemoTrackData {
        id: 2,
        name: "Stradivarius Cello",
        color_rgb: [234, 179, 8], // Gold / Amber
        is_audio: false,
        gain: 0.90,
        pan: 0.15,
        preset_id: "stradivarius_cello",
        clip_start_beat: 0.0,
        clip_length_beats: 16.0,
        notes: &[
            (1, 0.0, 4.0, 0.85),
            (3, 4.0, 4.0, 0.80),
            (5, 8.0, 4.0, 0.90),
            (1, 12.0, 4.0, 0.85),
        ],
    },
    DemoTrackData {
        id: 3,
        name: "Bamboo Shakuhachi",
        color_rgb: [16, 185, 129], // Emerald
        is_audio: false,
        gain: 0.85,
        pan: -0.25,
        preset_id: "shakuhachi_flute",
        clip_start_beat: 4.0,
        clip_length_beats: 12.0,
        notes: &[
            (8, 4.0, 3.0, 0.75),
            (10, 7.5, 2.0, 0.80),
            (12, 10.0, 3.5, 0.85),
            (15, 14.0, 2.0, 0.70),
        ],
    },
    DemoTrackData {
        id: 4,
        name: "Hindustani Sitar",
        color_rgb: [236, 72, 153], // Magenta
        is_audio: false,
        gain: 0.80,
        pan: 0.30,
        preset_id: "ravi_sitar",
        clip_start_beat: 2.0,
        clip_length_beats: 14.0,
        notes: &[
            (5, 2.0, 1.0, 0.80),
            (7, 3.0, 1.0, 0.85),
            (8, 6.0, 1.5, 0.90),
            (10, 8.0, 2.0, 0.80),
            (12, 12.0, 3.0, 0.95),
        ],
    },
    DemoTrackData {
        id: 5,
        name: "Concert Marimba",
        color_rgb: [168, 85, 247], // Purple
        is_audio: false,
        gain: 0.85,
        pan: 0.00,
        preset_id: "rosewood_marimba",
        clip_start_beat: 0.0,
        clip_length_beats: 16.0,
        notes: &[
            (3, 0.0, 0.5, 0.70),
            (8, 1.0, 0.5, 0.75),
            (5, 2.0, 0.5, 0.70),
            (10, 3.0, 0.5, 0.80),
            (8, 4.0, 0.5, 0.75),
            (12, 5.0, 0.5, 0.85),
            (10, 6.0, 0.5, 0.80),
            (15, 7.0, 0.5, 0.90),
        ],
    },
];

pub static DEMO_19_EDO_TRACKS: &[DemoTrackData] = &[
    DemoTrackData {
        id: 1,
        name: "19-EDO Neutral Pad",
        color_rgb: [139, 92, 246],
        is_audio: false,
        gain: 0.90,
        pan: -0.20,
        preset_id: "19_edo_neutral_pad",
        clip_start_beat: 0.0,
        clip_length_beats: 16.0,
        notes: &[
            (0, 0.0, 8.0, 0.85),
            (6, 0.0, 8.0, 0.80),
            (11, 0.0, 8.0, 0.85),
            (3, 8.0, 8.0, 0.85),
            (9, 8.0, 8.0, 0.80),
            (14, 8.0, 8.0, 0.85),
        ],
    },
    DemoTrackData {
        id: 2,
        name: "19-EDO Sub Bass",
        color_rgb: [56, 189, 248],
        is_audio: false,
        gain: 1.00,
        pan: 0.00,
        preset_id: "22_edo_porcupine_bass",
        clip_start_beat: 0.0,
        clip_length_beats: 16.0,
        notes: &[
            (0, 0.0, 4.0, 0.95),
            (6, 4.0, 4.0, 0.90),
            (3, 8.0, 4.0, 0.95),
            (9, 12.0, 4.0, 0.90),
        ],
    },
    DemoTrackData {
        id: 3,
        name: "Quartertone Pluck",
        color_rgb: [245, 158, 11],
        is_audio: false,
        gain: 0.85,
        pan: 0.25,
        preset_id: "31_edo_justness_lead",
        clip_start_beat: 2.0,
        clip_length_beats: 14.0,
        notes: &[
            (5, 2.0, 1.0, 0.80),
            (8, 3.5, 1.0, 0.85),
            (11, 5.0, 1.5, 0.90),
            (14, 7.0, 2.0, 0.85),
            (17, 10.0, 3.0, 0.95),
        ],
    },
    DemoTrackData {
        id: 4,
        name: "53-EDO Makam Lead",
        color_rgb: [16, 185, 129],
        is_audio: false,
        gain: 0.80,
        pan: -0.10,
        preset_id: "53_edo_makam_drone",
        clip_start_beat: 4.0,
        clip_length_beats: 12.0,
        notes: &[
            (9, 4.0, 3.0, 0.80),
            (12, 7.5, 2.5, 0.85),
            (16, 11.0, 4.0, 0.90),
        ],
    },
];

pub static DEMO_BOHLEN_PIERCE_TRACKS: &[DemoTrackData] = &[
    DemoTrackData {
        id: 1,
        name: "BP Crystal Chime",
        color_rgb: [56, 189, 248],
        is_audio: false,
        gain: 0.90,
        pan: -0.20,
        preset_id: "bp_gamma_chime",
        clip_start_beat: 0.0,
        clip_length_beats: 12.0,
        notes: &[
            (0, 0.0, 2.0, 0.85),
            (3, 2.0, 2.0, 0.80),
            (6, 4.0, 3.0, 0.90),
            (9, 7.0, 2.0, 0.85),
            (12, 9.0, 3.0, 0.95),
        ],
    },
    DemoTrackData {
        id: 2,
        name: "Tritave Drone Organ",
        color_rgb: [168, 85, 247],
        is_audio: false,
        gain: 0.85,
        pan: 0.15,
        preset_id: "baroque_pipe_organ",
        clip_start_beat: 0.0,
        clip_length_beats: 12.0,
        notes: &[
            (0, 0.0, 6.0, 0.80),
            (6, 6.0, 6.0, 0.85),
        ],
    },
    DemoTrackData {
        id: 3,
        name: "Glass Armonica Shimmer",
        color_rgb: [236, 72, 153],
        is_audio: false,
        gain: 0.80,
        pan: 0.30,
        preset_id: "glass_armonica",
        clip_start_beat: 3.0,
        clip_length_beats: 9.0,
        notes: &[
            (6, 3.0, 3.0, 0.75),
            (9, 6.0, 3.0, 0.85),
            (12, 9.0, 3.0, 0.90),
        ],
    },
    DemoTrackData {
        id: 4,
        name: "Acoustic Plate Tank",
        color_rgb: [14, 165, 233],
        is_audio: true,
        gain: 0.75,
        pan: 0.00,
        preset_id: "emt140_plate_reverb",
        clip_start_beat: 0.0,
        clip_length_beats: 12.0,
        notes: &[],
    },
];

pub static DEMO_CHIPTUNE_TRACKS: &[DemoTrackData] = &[
    DemoTrackData {
        id: 1,
        name: "NES 8-Bit Pulse Lead",
        color_rgb: [239, 68, 68],
        is_audio: false,
        gain: 0.95,
        pan: -0.10,
        preset_id: "nes_pulse_lead",
        clip_start_beat: 0.0,
        clip_length_beats: 16.0,
        notes: &[
            (7, 0.0, 0.5, 0.90),
            (10, 0.5, 0.5, 0.85),
            (12, 1.0, 1.0, 0.95),
            (15, 2.5, 0.5, 0.90),
            (14, 3.0, 1.0, 0.85),
            (12, 4.5, 1.5, 0.90),
            (10, 6.0, 2.0, 0.80),
        ],
    },
    DemoTrackData {
        id: 2,
        name: "GameBoy Triangle Bass",
        color_rgb: [34, 197, 94],
        is_audio: false,
        gain: 1.00,
        pan: 0.00,
        preset_id: "gameboy_triangle_bass",
        clip_start_beat: 0.0,
        clip_length_beats: 16.0,
        notes: &[
            (0, 0.0, 1.0, 1.00),
            (0, 1.5, 0.5, 0.90),
            (3, 2.0, 1.0, 0.95),
            (5, 3.0, 1.0, 1.00),
            (0, 4.0, 1.0, 1.00),
        ],
    },
    DemoTrackData {
        id: 3,
        name: "SID 6581 Arpeggiator",
        color_rgb: [234, 179, 8],
        is_audio: false,
        gain: 0.85,
        pan: 0.20,
        preset_id: "sid_6581_arp",
        clip_start_beat: 0.0,
        clip_length_beats: 16.0,
        notes: &[
            (7, 0.0, 0.25, 0.80),
            (10, 0.25, 0.25, 0.80),
            (14, 0.50, 0.25, 0.80),
            (19, 0.75, 0.25, 0.85),
        ],
    },
    DemoTrackData {
        id: 4,
        name: "8-Bit Noise Drums",
        color_rgb: [168, 85, 247],
        is_audio: false,
        gain: 0.90,
        pan: 0.00,
        preset_id: "chiptune_noise_drums",
        clip_start_beat: 0.0,
        clip_length_beats: 16.0,
        notes: &[
            (2, 0.0, 0.2, 0.95), // Kick
            (5, 1.0, 0.2, 0.90), // Snare
            (2, 2.0, 0.2, 0.95), // Kick
            (5, 3.0, 0.2, 0.90), // Snare
        ],
    },
];

pub static DEMO_GM_QUINTET_TRACKS: &[DemoTrackData] = &[
    DemoTrackData {
        id: 1,
        name: "GM Acoustic Grand Piano",
        color_rgb: [56, 189, 248],
        is_audio: false,
        gain: 0.95,
        pan: -0.15,
        preset_id: "gm_grand_piano",
        clip_start_beat: 0.0,
        clip_length_beats: 16.0,
        notes: &[
            (0, 0.0, 2.0, 0.85),
            (4, 2.0, 2.0, 0.80),
            (7, 4.0, 2.0, 0.85),
            (12, 6.0, 2.0, 0.90),
            (7, 8.0, 2.0, 0.85),
            (4, 10.0, 2.0, 0.80),
            (0, 12.0, 4.0, 0.95),
        ],
    },
    DemoTrackData {
        id: 2,
        name: "GM Acoustic Bass",
        color_rgb: [245, 158, 11],
        is_audio: false,
        gain: 0.95,
        pan: 0.00,
        preset_id: "gm_acoustic_bass",
        clip_start_beat: 0.0,
        clip_length_beats: 16.0,
        notes: &[
            (0, 0.0, 4.0, 0.95),
            (5, 4.0, 4.0, 0.90),
            (7, 8.0, 4.0, 0.95),
            (0, 12.0, 4.0, 0.95),
        ],
    },
    DemoTrackData {
        id: 3,
        name: "GM Standard Drum Kit",
        color_rgb: [239, 68, 68],
        is_audio: false,
        gain: 0.90,
        pan: 0.00,
        preset_id: "gm_standard_drums",
        clip_start_beat: 0.0,
        clip_length_beats: 16.0,
        notes: &[
            (1, 0.0, 0.2, 0.95),
            (3, 1.0, 0.2, 0.90),
            (1, 2.0, 0.2, 0.95),
            (3, 3.0, 0.2, 0.90),
        ],
    },
    DemoTrackData {
        id: 4,
        name: "GM Drawbar Organ",
        color_rgb: [16, 185, 129],
        is_audio: false,
        gain: 0.80,
        pan: 0.20,
        preset_id: "gm_drawbar_organ",
        clip_start_beat: 0.0,
        clip_length_beats: 16.0,
        notes: &[
            (7, 0.0, 8.0, 0.75),
            (12, 8.0, 8.0, 0.80),
        ],
    },
    DemoTrackData {
        id: 5,
        name: "GM Synth Brass 1",
        color_rgb: [236, 72, 153],
        is_audio: false,
        gain: 0.85,
        pan: -0.20,
        preset_id: "gm_synth_brass",
        clip_start_beat: 4.0,
        clip_length_beats: 12.0,
        notes: &[
            (12, 4.0, 1.5, 0.85),
            (16, 6.0, 2.0, 0.90),
            (19, 8.5, 3.5, 0.95),
        ],
    },
];

pub static FACTORY_DEMO_TEMPLATES: &[FactoryDemoTemplate] = &[
    FactoryDemoTemplate {
        id: "physical_showcase",
        title: "Physical Modeling Acoustic Showcase",
        description: "Acoustic chamber ensemble featuring concert grand piano, Cremona bowed cello, Japanese Shakuhachi, Indian sitar, and rosewood marimba.",
        bpm: 110.0,
        key_signature: "C Maj",
        time_signature: "4/4",
        tuning_name: "12-EDO Standard (A=440Hz)",
        tuning_edo: None,
        tracks: DEMO_SHOWCASE_TRACKS,
    },
    FactoryDemoTemplate {
        id: "19_edo_odyssey",
        title: "19-EDO Microtonal Odyssey",
        description: "19 Equal Divisions of the Octave arrangement with pure neutral thirds, microtonal basslines, and quartertone plucks.",
        bpm: 128.0,
        key_signature: "19-EDO C",
        time_signature: "4/4",
        tuning_name: "19-EDO (Microtonal Meantone)",
        tuning_edo: Some(19),
        tracks: DEMO_19_EDO_TRACKS,
    },
    FactoryDemoTemplate {
        id: "bohlen_pierce",
        title: "Bohlen-Pierce Tritave Ambient",
        description: "Non-octave 13-division tritave (3:1) meditative soundscape with odd harmonic crystals, sacred organs, and plate reverberation.",
        bpm: 88.0,
        key_signature: "BP Gamma",
        time_signature: "3/4",
        tuning_name: "Bohlen-Pierce 13-EDT (Non-Octave)",
        tuning_edo: None,
        tracks: DEMO_BOHLEN_PIERCE_TRACKS,
    },
    FactoryDemoTemplate {
        id: "chiptune_anthem",
        title: "Chiptune Tracker 8-Bit Anthem",
        description: "Authentic 1980s 8-bit tracker groove with dual NES pulse channels, GameBoy triangle bass, SID arpeggiators, and LFSR noise percussion.",
        bpm: 144.0,
        key_signature: "D Min",
        time_signature: "4/4",
        tuning_name: "12-EDO Equal Temperament",
        tuning_edo: None,
        tracks: DEMO_CHIPTUNE_TRACKS,
    },
    FactoryDemoTemplate {
        id: "gm_quintet",
        title: "General MIDI Standard Quintet",
        description: "Standard General MIDI 5-piece arrangement (Piano, Upright Bass, Drums, Drawbar Organ, Synth Brass) matching MIDI GM Level 1 spec.",
        bpm: 120.0,
        key_signature: "A Min",
        time_signature: "4/4",
        tuning_name: "12-EDO Standard (A=440Hz)",
        tuning_edo: None,
        tracks: DEMO_GM_QUINTET_TRACKS,
    },
];

/// Returns all curated factory presets.
pub fn all_factory_presets() -> &'static [FactoryPreset] {
    FACTORY_PRESETS
}

/// Finds a factory preset by case-insensitive name or ID.
pub fn find_preset(name_or_id: &str) -> Option<&'static FactoryPreset> {
    let query = name_or_id.trim().to_lowercase();
    FACTORY_PRESETS.iter().find(|p| {
        p.id.eq_ignore_ascii_case(&query)
            || p.name.eq_ignore_ascii_case(&query)
            || query.contains(&p.id.to_lowercase())
            || query.contains(&p.name.to_lowercase())
    })
}

/// Returns presets belonging to a specific category.
pub fn presets_by_category(cat: FactoryPresetCategory) -> Vec<&'static FactoryPreset> {
    FACTORY_PRESETS.iter().filter(|p| p.category == cat).collect()
}

/// Returns all demo project templates.
pub fn all_demo_templates() -> &'static [FactoryDemoTemplate] {
    FACTORY_DEMO_TEMPLATES
}

/// Finds a demo project template by case-insensitive ID or title.
pub fn find_demo_template(id_or_title: &str) -> Option<&'static FactoryDemoTemplate> {
    let query = id_or_title.trim().to_lowercase();
    FACTORY_DEMO_TEMPLATES.iter().find(|t| {
        t.id.eq_ignore_ascii_case(&query)
            || t.title.eq_ignore_ascii_case(&query)
            || query.contains(&t.id.to_lowercase())
            || query.contains(&t.title.to_lowercase())
    })
}
