// Summoner - Deterministic, Headless-First DAW
// Copyright (C) 2026 nilsanderselde
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU Affero General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
// GNU Affero General Public License for more details.

//! GPU-accelerated UI & LOD rendering engine for Summoner DAW.

#![allow(clippy::new_without_default)]

pub mod ascii_renderer;
pub mod docking_layout;
pub mod gpu_waveform;
pub mod hud_overlay;
pub mod layout_math;
pub mod lod;
pub mod oscilloscope_view;
pub mod platform;
pub mod renderer;
pub mod touch_controls;
pub mod visualizer;
pub mod waveform_cache;

#[cfg(feature = "gui")]
pub mod app;
#[cfg(feature = "gui")]
pub mod command_palette;
#[cfg(feature = "gui")]
pub mod param_controls;
#[cfg(feature = "gui")]
pub mod patch_matrix;
#[cfg(feature = "gui")]
pub mod stage_view;
#[cfg(feature = "gui")]
pub mod theme;
#[cfg(feature = "gui")]
pub mod tier32_tests;
#[cfg(feature = "gui")]
pub mod tier33_advanced_tests;
#[cfg(feature = "gui")]
pub mod tier33_tests;
#[cfg(feature = "gui")]
pub mod tier34_tests;
pub mod tier35_tests;
pub mod tier36_tests;
pub mod tier37_tests;
pub mod tier38_tests;
pub mod tier39_tests;
pub mod tier40_tests;
pub mod tier41_tests;
pub mod tier43_tests;
pub mod tier44_tests;
pub mod tier45_tests;
pub mod tier46_tests;
pub mod tier47_tests;
#[cfg(feature = "gui")]
pub mod tier48_tests;
#[cfg(feature = "gui")]
pub mod tier49_tests;
#[cfg(feature = "gui")]
pub mod tier50_tests;
#[cfg(feature = "gui")]
pub mod tier51_tests;
#[cfg(feature = "gui")]
pub mod tier52_tests;
#[cfg(feature = "gui")]
pub mod tier53_tests;
#[cfg(feature = "gui")]
pub mod tier54_tests;
#[cfg(feature = "gui")]
pub mod tier55_tests;
#[cfg(feature = "gui")]
pub mod tier56_tests;
#[cfg(feature = "gui")]
pub mod tier57_tests;
#[cfg(feature = "gui")]
pub mod tier58_tests;
#[cfg(feature = "gui")]
pub mod tier59_tests;
#[cfg(feature = "gui")]
pub mod tier60_tests;
#[cfg(feature = "gui")]
pub mod tier61_tests;
#[cfg(feature = "gui")]
pub mod tier62_tests;
#[cfg(feature = "gui")]
pub mod tier63_tests;
#[cfg(feature = "gui")]
pub mod tier64_tests;
#[cfg(feature = "gui")]
pub mod tier65_tests;
#[cfg(feature = "gui")]
pub mod tier66_tests;
#[cfg(feature = "gui")]
pub mod tier67_tests;
#[cfg(feature = "gui")]
pub mod tier68_tests;
#[cfg(feature = "gui")]
pub mod tier69_tests;
#[cfg(feature = "gui")]
pub mod tier70_tests;
#[cfg(feature = "gui")]
pub mod tier71_tests;
#[cfg(feature = "gui")]
pub mod touch_gestures;
#[cfg(feature = "gui")]
pub mod transport_bar;
#[cfg(feature = "gui")]
pub mod views;

#[cfg(feature = "gui")]
pub use views::accessibility_announcer::AccessibilityAnnouncerView;
#[cfg(feature = "gui")]
pub use views::ambisonic_radar_view::AmbisonicRadarView;
#[cfg(feature = "gui")]
pub use views::atmos_surround_view::AtmosSurroundView;
#[cfg(feature = "gui")]
pub use views::auro3d_spatializer_view::Auro3dSpatializerView;
#[cfg(feature = "gui")]
pub use views::bbd_chorus_view::BbdChorusView;
#[cfg(feature = "gui")]
pub use views::bezier_automation_editor::BezierAutomationEditorView;
#[cfg(feature = "gui")]
pub use views::binaural_brir_view::BinauralBrirView;
#[cfg(feature = "gui")]
pub use views::binaural_panner_view::BinauralPannerView;
#[cfg(feature = "gui")]
pub use views::bitcrusher_morph_view::BitcrusherMorphView;
#[cfg(feature = "gui")]
pub use views::bowed_string_view::BowedStringView;
#[cfg(feature = "gui")]
pub use views::comb_resonator_view::CombResonatorView;
#[cfg(feature = "gui")]
pub use views::convolution_impulse_view::ConvolutionImpulseView;
#[cfg(feature = "gui")]
pub use views::convolution_morph_view::ConvolutionMorphView;
#[cfg(feature = "gui")]
pub use views::detachable_window_manager::DetachableWindowManagerView;
#[cfg(feature = "gui")]
pub use views::dialog_gating_view::DialogGatingView;
#[cfg(feature = "gui")]
pub use views::dpi_scale_panel::DpiScalePanelView;
#[cfg(feature = "gui")]
pub use views::dsp_rack_dock::DspRackDockView;
#[cfg(feature = "gui")]
pub use views::dynamic_crest_shaper_view::DynamicCrestShaperView;
#[cfg(feature = "gui")]
pub use views::ebu_loudness_radar_view::EbuLoudnessRadarView;
#[cfg(feature = "gui")]
pub use views::envelope_follower_view::EnvelopeFollowerView;
#[cfg(feature = "gui")]
pub use views::fm_matrix_view::FmMatrixView;
#[cfg(feature = "gui")]
pub use views::formant_filter_view::FormantFilterView;
#[cfg(feature = "gui")]
pub use views::frequency_shifter_view::FrequencyShifterView;
#[cfg(feature = "gui")]
pub use views::glass_armonica_view::GlassArmonicaView;
#[cfg(feature = "gui")]
pub use views::granular_cloud_view::GranularCloudView;
#[cfg(feature = "gui")]
pub use views::granular_freeze_view::GranularFreezeView;
#[cfg(feature = "gui")]
pub use views::granular_pitch_shifter_view::GranularPitchShifterView;
#[cfg(feature = "gui")]
pub use views::harmonic_exciter_view::HarmonicExciterView;
#[cfg(feature = "gui")]
pub use views::harmonic_tension_map::HarmonicTensionMapView;
#[cfg(feature = "gui")]
pub use views::hoa4_spatializer_view::Hoa4SpatializerView;
#[cfg(feature = "gui")]
pub use views::hoa_spatializer_view::HoaSpatializerView;
#[cfg(feature = "gui")]
pub use views::isomorphic_tuning_keyboard::IsomorphicTuningKeyboardView;
#[cfg(feature = "gui")]
pub use views::k_system_meter_view::KSystemMeterView;
#[cfg(feature = "gui")]
pub use views::keybinding_editor::KeybindingEditorView;
#[cfg(feature = "gui")]
pub use views::ladder_filter_view::LadderFilterView;
#[cfg(feature = "gui")]
pub use views::linear_phase_crossover_view::LinearPhaseCrossoverView;
#[cfg(feature = "gui")]
pub use views::live_macro_rack::LiveMacroRackView;
#[cfg(feature = "gui")]
pub use views::loop_slicer_view::LoopSlicerView;
#[cfg(feature = "gui")]
pub use views::macro_rotary_dial::MacroRotaryDialView;
#[cfg(feature = "gui")]
pub use views::master_limiter_radar_view::MasterLimiterRadarView;
#[cfg(feature = "gui")]
pub use views::mbira_kalimba_view::MbiraKalimbaView;
#[cfg(feature = "gui")]
pub use views::membrane_plate_view::MembranePlateView;
#[cfg(feature = "gui")]
pub use views::membrane_resonator_view::MembraneResonatorView;
#[cfg(feature = "gui")]
pub use views::meter_bridge_view::MeterBridgeView;
#[cfg(feature = "gui")]
pub use views::mpegh_3d_spatializer_view::Mpegh3DSpatializerView;
#[cfg(feature = "gui")]
pub use views::mpegh_spatializer_view::MpeghSpatializerView;
#[cfg(feature = "gui")]
pub use views::multiband_clipper_view::MultibandClipperView;
#[cfg(feature = "gui")]
pub use views::multiband_decompressor_view::MultibandDecompressorView;
#[cfg(feature = "gui")]
pub use views::multiband_expander_view::MultibandExpanderView;
#[cfg(feature = "gui")]
pub use views::multiband_imager_view::MultibandImagerView;
#[cfg(feature = "gui")]
pub use views::multiband_saturator_view::MultibandSaturatorView;
#[cfg(feature = "gui")]
pub use views::multiband_spatial_view::MultibandSpatialView;
#[cfg(feature = "gui")]
pub use views::multitap_delay_view::MultitapDelayView;
#[cfg(feature = "gui")]
pub use views::neural_inpaint_view::NeuralInpaintView;
#[cfg(feature = "gui")]
pub use views::neural_phoneme_view::NeuralPhonemeView;
#[cfg(feature = "gui")]
pub use views::neural_speech_to_singing_view::NeuralSpeechToSingingView;
#[cfg(feature = "gui")]
pub use views::neural_timbre_morph_view::NeuralTimbreMorphView;
#[cfg(feature = "gui")]
pub use views::neural_timbre_view::NeuralTimbreView;
#[cfg(feature = "gui")]
pub use views::neural_vocal_stylizer_view::NeuralVocalStylizerView;
#[cfg(feature = "gui")]
pub use views::neural_vocoder_morph_view::NeuralVocoderMorphView;
#[cfg(feature = "gui")]
pub use views::neural_wavetable_view::NeuralWavetableView;
#[cfg(feature = "gui")]
pub use views::nhk222_spatializer_view::Nhk222SpatializerView;
#[cfg(feature = "gui")]
pub use views::optical_compressor_view::OpticalCompressorView;
#[cfg(feature = "gui")]
pub use views::oversampled_limiter_view::OversampledLimiterView;
#[cfg(feature = "gui")]
pub use views::parallel_transient_saturator_view::ParallelTransientSaturatorView;
#[cfg(feature = "gui")]
pub use views::phase_align_view::PhaseAlignView;
#[cfg(feature = "gui")]
pub use views::pipe_organ_view::PipeOrganView;
#[cfg(feature = "gui")]
pub use views::pitch_corrector_view::PitchCorrectorView;
#[cfg(feature = "gui")]
pub use views::polar_phase_correlator_view::PolarPhaseCorrelatorView;
#[cfg(feature = "gui")]
pub use views::raytraced_reverb_view::RaytracedReverbView;
#[cfg(feature = "gui")]
pub use views::resonance_suppressor_view::ResonanceSuppressorView;
#[cfg(feature = "gui")]
pub use views::reverb_space_view::ReverbSpaceView;
#[cfg(feature = "gui")]
pub use views::ribbon_controller_view::RibbonControllerView;
#[cfg(feature = "gui")]
pub use views::rotary_doppler_view::RotaryDopplerView;
#[cfg(feature = "gui")]
pub use views::rotary_speaker_view::RotarySpeakerView;
#[cfg(feature = "gui")]
pub use views::sample_editor_view;
#[cfg(feature = "gui")]
pub use views::sample_editor_view::SampleEditorView;
#[cfg(feature = "gui")]
pub use views::sidechain_matrix_view::SidechainMatrixView;
#[cfg(feature = "gui")]
pub use views::sonar_hydrophone_view::SonarHydrophoneView;
#[cfg(feature = "gui")]
pub use views::spatial_panner_view::SpatialPannerView;
#[cfg(feature = "gui")]
pub use views::spectral_aligner_view::SpectralAlignerView;
#[cfg(feature = "gui")]
pub use views::spectral_brush_editor::SpectralBrushEditorView;
#[cfg(feature = "gui")]
pub use views::spectral_debleed_view::SpectralDebleedView;
#[cfg(feature = "gui")]
pub use views::spectral_deesser_view::SpectralDeEsserView;
#[cfg(feature = "gui")]
pub use views::spectral_grain_cloud_view::SpectralGrainCloudView;
#[cfg(feature = "gui")]
pub use views::spectral_matching_eq_view::SpectralMatchingEqView;
#[cfg(feature = "gui")]
pub use views::spectral_morph_view::SpectralMorphView;
#[cfg(feature = "gui")]
pub use views::spectral_reshaper_view::SpectralReshaperView;
#[cfg(feature = "gui")]
pub use views::spectral_resynthesis_view::SpectralResynthesisView;
#[cfg(feature = "gui")]
pub use views::spectral_tilt_view::SpectralTiltView;
#[cfg(feature = "gui")]
pub use views::spectrogram_3d_view::Spectrogram3DView;
#[cfg(feature = "gui")]
pub use views::spring_reverb_view::SpringReverbView;
#[cfg(feature = "gui")]
pub use views::step_sequencer_matrix::StepSequencerMatrixView;
#[cfg(feature = "gui")]
pub use views::stereo_vectorscope_view::StereoVectorscopeView;
#[cfg(feature = "gui")]
pub use views::stereo_widener_view::StereoWidenerView;
#[cfg(feature = "gui")]
pub use views::subharmonic_synth_view::SubharmonicSynthView;
#[cfg(feature = "gui")]
pub use views::tape_emulator_view::TapeEmulatorView;
#[cfg(feature = "gui")]
pub use views::tape_flutter_view::TapeFlutterView;
#[cfg(feature = "gui")]
pub use views::through_zero_flanger_view::ThroughZeroFlangerView;
#[cfg(feature = "gui")]
pub use views::transient_designer_view::TransientDesignerView;
#[cfg(feature = "gui")]
pub use views::transient_gate_view::TransientGateView;
#[cfg(feature = "gui")]
pub use views::transient_shaper_view::TransientShaperView;
#[cfg(feature = "gui")]
pub use views::transient_unwrapper_view::TransientUnwrapperView;
#[cfg(feature = "gui")]
pub use views::transient_warp_editor::TransientWarpEditorView;
#[cfg(feature = "gui")]
pub use views::tube_bias_view::TubeBiasView;
#[cfg(feature = "gui")]
pub use views::upward_compressor_view::UpwardCompressorView;
#[cfg(feature = "gui")]
pub use views::vari_mu_master_view::VariMuMasterView;
#[cfg(feature = "gui")]
pub use views::vocoder_matrix_view::VocoderMatrixView;
#[cfg(feature = "gui")]
pub use views::waveguide_brass_view::WaveguideBrassView;
#[cfg(feature = "gui")]
pub use views::wfs_array_spatializer_view::WfsArraySpatializerView;
#[cfg(feature = "gui")]
pub use views::woodwind_jet_view::WoodwindJetView;

#[cfg(feature = "gui")]
pub fn launch(
    project: summoner_project::schema::ProjectConfig,
    param_bus: std::sync::Arc<summoner_core::param_bus::ParamBus>,
) {
    let native_options = eframe::NativeOptions::default();
    eframe::run_native(
        "Summoner DAW",
        native_options,
        Box::new(|_cc| Ok(Box::new(app::SummonerApp::new(project, param_bus)))),
    )
    .unwrap();
}
