// Summoner - Deterministic, Headless-First DAW
// Copyright (C) 2026 nilsanderselde - AGPLv3 License

//! Generative Polyrhythmic Sequence Mutator & Higher-Order Markov Harmony Graph (Milestone 10).
//!
//! Implements 2nd and 3rd-order Markov chain sequence generators with temperature-scaled
//! transition probabilities, full TOML/JSON serialization of transition matrices,
//! polyrhythmic step division engines, and sample-accurate lock-free dispatch into
//! `ParamBus` and sequencer timeline structures.

use crate::pattern::{PatternClip, PatternStep};
use crate::timeline::{Clip, ClipContent, PatternNote, TimelineArranger};
use serde::{Deserialize, Serialize};
use std::collections::BTreeMap;
use summoner_core::param_bus::{ParamBus, ParamId};
use summoner_project::schema::TrackerStepConfig;

/// Markov model order configuration.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize, Default)]
pub enum MarkovOrder {
    /// 2nd-order Markov chain: transition conditioned on the 2 preceding steps.
    #[default]
    Order2 = 2,
    /// 3rd-order Markov chain: transition conditioned on the 3 preceding steps.
    Order3 = 3,
}

/// Polyrhythmic step division defining step durations relative to quarter note beats.
#[derive(Debug, Clone, Copy, PartialEq, Serialize, Deserialize, Default)]
pub enum PolyrhythmicDivision {
    Quarter,        // 1.0 beat (1/4)
    Eighth,         // 0.5 beat (1/8)
    #[default]
    Sixteenth,      // 0.25 beat (1/16)
    ThirtySecond,   // 0.125 beat (1/32)
    Triplet8th,     // 1/3 beat (8th triplet)
    Triplet16th,    // 1/6 beat (16th triplet)
    Quintuplet16th, // 1/5 beat (5:4 16th quintuplet)
    Septuplet16th,  // 1/7 beat (7:4 16th septuplet)
    DottedEighth,   // 0.75 beat (3/16)
    Custom(f64),    // Arbitrary fractional beat duration
}

impl PolyrhythmicDivision {
    /// Duration of a single step in beats (where 1.0 beat = 1 quarter note).
    pub fn step_beats(&self) -> f64 {
        match self {
            PolyrhythmicDivision::Quarter => 1.0,
            PolyrhythmicDivision::Eighth => 0.5,
            PolyrhythmicDivision::Sixteenth => 0.25,
            PolyrhythmicDivision::ThirtySecond => 0.125,
            PolyrhythmicDivision::Triplet8th => 1.0 / 3.0,
            PolyrhythmicDivision::Triplet16th => 1.0 / 6.0,
            PolyrhythmicDivision::Quintuplet16th => 1.0 / 5.0,
            PolyrhythmicDivision::Septuplet16th => 1.0 / 7.0,
            PolyrhythmicDivision::DottedEighth => 0.75,
            PolyrhythmicDivision::Custom(beats) => *beats,
        }
    }

    /// Nominal number of steps per standard 4-beat measure.
    pub fn steps_per_measure(&self) -> usize {
        (4.0 / self.step_beats()).round().max(1.0) as usize
    }
}

/// A musical step event generated by the Markov chain engine.
#[derive(Debug, Clone, Copy, PartialEq, Serialize, Deserialize)]
pub struct MarkovStepEvent {
    /// MIDI pitch number (e.g. 60.0 = C4, fractional values support microtonal tuning).
    pub pitch: f32,
    /// Note velocity (0.0 to 1.0).
    pub velocity: f32,
    /// Gate duration fraction (0.0 to 1.0).
    pub gate: f32,
    /// Trigger probability (0.0 to 1.0).
    pub probability: f32,
    /// Sub-step ratchet subdivision multiplier (1 to 8).
    pub ratchet: u8,
    /// Micro-shift timing offset in ticks (-100 to 100).
    pub micro_shift: i8,
    /// Pitch offset fine-tuning in cents.
    pub pitch_offset: f32,
    /// Step active state.
    pub active: bool,
}

impl Default for MarkovStepEvent {
    fn default() -> Self {
        Self {
            pitch: 60.0,
            velocity: 0.8,
            gate: 0.5,
            probability: 1.0,
            ratchet: 1,
            micro_shift: 0,
            pitch_offset: 0.0,
            active: true,
        }
    }
}

impl MarkovStepEvent {
    pub fn new(pitch: f32, velocity: f32, gate: f32) -> Self {
        Self {
            pitch,
            velocity: velocity.clamp(0.0, 1.0),
            gate: gate.clamp(0.0, 1.0),
            ..Default::default()
        }
    }

    /// Convert to project-level TrackerStepConfig.
    pub fn to_tracker_step(&self) -> TrackerStepConfig {
        TrackerStepConfig {
            note: self.pitch as f64,
            velocity: self.velocity,
            gate: self.gate,
            probability: self.probability,
            ratchet: self.ratchet as u32,
            micro_shift: self.micro_shift as i32,
            swing: 0.0,
            pan: 0.0,
            pitch_offset: self.pitch_offset,
            active: self.active,
            muted: false,
        }
    }

    /// Construct from project TrackerStepConfig.
    pub fn from_tracker_step(step: &TrackerStepConfig) -> Self {
        Self {
            pitch: step.note as f32,
            velocity: step.velocity,
            gate: step.gate,
            probability: step.probability,
            ratchet: step.ratchet.min(255) as u8,
            micro_shift: step.micro_shift.clamp(-128, 127) as i8,
            pitch_offset: step.pitch_offset,
            active: step.active && !step.muted,
        }
    }
}

/// Serialized transition weights table for Markov chains.
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct MarkovTransitionMatrix {
    /// 2nd-order transitions: (pitch1_cents, pitch2_cents) -> list of (event, raw_count)
    pub transitions_order2: BTreeMap<(u16, u16), Vec<(MarkovStepEvent, u32)>>,
    /// 3rd-order transitions: (pitch1_cents, pitch2_cents, pitch3_cents) -> list of (event, raw_count)
    pub transitions_order3: BTreeMap<(u16, u16, u16), Vec<(MarkovStepEvent, u32)>>,
}

/// Configuration parameters for sequence generation and mutation.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct MarkovMutatorConfig {
    /// Order of Markov chain dependency.
    pub order: MarkovOrder,
    /// Generation temperature (0.1 = strict/deterministic, 1.0 = standard, 2.5 = chaotic).
    pub temperature: f32,
    /// Mutation probability for each step (0.0 = preserve original, 1.0 = mutate all).
    pub mutation_rate: f32,
    /// Polyrhythmic step division.
    pub division: PolyrhythmicDivision,
    /// Constrain output pitches to specific scale degrees/intervals (if set).
    pub scale_degrees: Option<Vec<f32>>,
    /// Preserve original rhythm and only mutate pitches.
    pub pitch_only: bool,
}

impl Default for MarkovMutatorConfig {
    fn default() -> Self {
        Self {
            order: MarkovOrder::Order2,
            temperature: 1.0,
            mutation_rate: 0.35,
            division: PolyrhythmicDivision::Sixteenth,
            scale_degrees: None,
            pitch_only: false,
        }
    }
}

/// Generative Polyrhythmic Sequence Mutator & Higher-Order Markov Harmony Graph Engine.
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct MarkovSequenceMutator {
    pub config: MarkovMutatorConfig,
    pub matrix: MarkovTransitionMatrix,
}

impl MarkovSequenceMutator {
    /// Create a new sequence mutator with default configuration.
    pub fn new() -> Self {
        Self {
            config: MarkovMutatorConfig::default(),
            matrix: MarkovTransitionMatrix::default(),
        }
    }

    /// Builder pattern configuring Markov order.
    pub fn with_order(mut self, order: MarkovOrder) -> Self {
        self.config.order = order;
        self
    }

    /// Builder pattern configuring temperature.
    pub fn with_temperature(mut self, temperature: f32) -> Self {
        self.config.temperature = temperature.max(0.01);
        self
    }

    /// Builder pattern configuring polyrhythmic step division.
    pub fn with_division(mut self, division: PolyrhythmicDivision) -> Self {
        self.config.division = division;
        self
    }

    /// Quantize pitch to discrete cent key integer (e.g. 60.0 -> 6000).
    fn pitch_to_key(pitch: f32) -> u16 {
        (pitch.clamp(0.0, 127.0) * 100.0).round() as u16
    }

    /// Train Markov transition matrix from a sequence of raw pitch numbers.
    pub fn train_from_pitches(&mut self, pitches: &[f32]) {
        let events: Vec<MarkovStepEvent> = pitches
            .iter()
            .map(|&p| MarkovStepEvent::new(p, 0.8, 0.5))
            .collect();
        self.train_from_events(&events);
    }

    /// Train Markov transition matrix from a sequence of TrackerStepConfigs.
    pub fn train_from_steps(&mut self, steps: &[TrackerStepConfig]) {
        let events: Vec<MarkovStepEvent> = steps
            .iter()
            .map(MarkovStepEvent::from_tracker_step)
            .collect();
        self.train_from_events(&events);
    }

    /// Train Markov model on a sequence of `MarkovStepEvent` instances.
    pub fn train_from_events(&mut self, events: &[MarkovStepEvent]) {
        if events.len() < 3 {
            return;
        }

        // 2nd-order training
        for win in events.windows(3) {
            let k1 = Self::pitch_to_key(win[0].pitch);
            let k2 = Self::pitch_to_key(win[1].pitch);
            let key = (k1, k2);
            let next_event = win[2];

            let candidates = self.matrix.transitions_order2.entry(key).or_default();
            if let Some(existing) = candidates.iter_mut().find(|(e, _)| (e.pitch - next_event.pitch).abs() < 0.01) {
                existing.1 += 1;
            } else {
                candidates.push((next_event, 1));
            }
        }

        // 3rd-order training
        if events.len() >= 4 {
            for win in events.windows(4) {
                let k1 = Self::pitch_to_key(win[0].pitch);
                let k2 = Self::pitch_to_key(win[1].pitch);
                let k3 = Self::pitch_to_key(win[2].pitch);
                let key = (k1, k2, k3);
                let next_event = win[3];

                let candidates = self.matrix.transitions_order3.entry(key).or_default();
                if let Some(existing) = candidates.iter_mut().find(|(e, _)| (e.pitch - next_event.pitch).abs() < 0.01) {
                    existing.1 += 1;
                } else {
                    candidates.push((next_event, 1));
                }
            }
        }
    }

    /// Pick next step event from weighted candidate distribution using temperature-scaled softmax sampling.
    fn sample_candidate(
        candidates: &[(MarkovStepEvent, u32)],
        temperature: f32,
        rng_seed: &mut u64,
    ) -> Option<MarkovStepEvent> {
        if candidates.is_empty() {
            return None;
        }

        // Deterministic linear congruential pseudo-random generator
        let mut prng_next = || {
            *rng_seed = rng_seed
                .wrapping_mul(6364136223846793005)
                .wrapping_add(1442695040888963407);
            ((*rng_seed >> 33) as f64) / 2147483648.0
        };

        let temp = temperature.max(0.01);
        let inv_temp = 1.0 / temp as f64;

        // Compute temperature-scaled weights: w_i = count^(1/T)
        let scaled_weights: Vec<f64> = candidates
            .iter()
            .map(|(_, count)| (*count as f64).powf(inv_temp))
            .collect();

        let total_weight: f64 = scaled_weights.iter().sum();
        if total_weight <= 0.0 {
            return Some(candidates[0].0);
        }

        let roll = prng_next() * total_weight;
        let mut accum = 0.0;
        for (i, &w) in scaled_weights.iter().enumerate() {
            accum += w;
            if roll <= accum || i == candidates.len() - 1 {
                return Some(candidates[i].0);
            }
        }

        Some(candidates.last().unwrap().0)
    }

    /// Generate a new sequence of `MarkovStepEvent`s deterministically from seed pitches.
    pub fn generate_sequence(
        &self,
        seed_pitches: &[f32],
        length: usize,
        mut rng_seed: u64,
    ) -> Vec<MarkovStepEvent> {
        if length == 0 {
            return Vec::new();
        }

        let mut result = Vec::with_capacity(length);

        // Populate initial seed steps
        for &p in seed_pitches.iter().take(length) {
            result.push(MarkovStepEvent::new(p, 0.8, 0.5));
        }

        while result.len() < length {
            let n = result.len();
            let chosen_event = match self.config.order {
                MarkovOrder::Order3 if n >= 3 => {
                    let k1 = Self::pitch_to_key(result[n - 3].pitch);
                    let k2 = Self::pitch_to_key(result[n - 2].pitch);
                    let k3 = Self::pitch_to_key(result[n - 1].pitch);
                    if let Some(cands) = self.matrix.transitions_order3.get(&(k1, k2, k3)) {
                        Self::sample_candidate(cands, self.config.temperature, &mut rng_seed)
                    } else if let Some(cands) = self.matrix.transitions_order2.get(&(k2, k3)) {
                        Self::sample_candidate(cands, self.config.temperature, &mut rng_seed)
                    } else {
                        None
                    }
                }
                _ if n >= 2 => {
                    let k1 = Self::pitch_to_key(result[n - 2].pitch);
                    let k2 = Self::pitch_to_key(result[n - 1].pitch);
                    if let Some(cands) = self.matrix.transitions_order2.get(&(k1, k2)) {
                        Self::sample_candidate(cands, self.config.temperature, &mut rng_seed)
                    } else {
                        None
                    }
                }
                _ => None,
            };

            let next_event = chosen_event.unwrap_or_else(|| {
                // Fallback deterministic harmonic continuation if unseen state
                let prev_p = if !result.is_empty() {
                    result[result.len() - 1].pitch
                } else {
                    60.0
                };
                let interval = match result.len() % 4 {
                    0 => 2.0,
                    1 => 3.0,
                    2 => -2.0,
                    _ => -3.0,
                };
                let new_p = (prev_p + interval).clamp(36.0, 96.0);
                MarkovStepEvent::new(new_p, 0.8, 0.5)
            });

            result.push(next_event);
        }

        // Apply scale degree snapping if scale_degrees is configured
        if let Some(scale) = &self.config.scale_degrees {
            if !scale.is_empty() {
                for ev in &mut result {
                    ev.pitch = snap_pitch_to_scale(ev.pitch, scale);
                }
            }
        }

        result
    }

    /// Mutate an existing array of TrackerStepConfigs based on mutation rate and Markov matrix.
    pub fn mutate_steps(
        &self,
        steps: &[TrackerStepConfig],
        mut rng_seed: u64,
    ) -> Vec<TrackerStepConfig> {
        let mut mutated = steps.to_vec();
        for i in 0..mutated.len() {
            if prng_next_f32(&mut rng_seed) < self.config.mutation_rate {
                // Attempt Markov prediction based on history
                let candidate = if i >= 2 {
                    let k1 = Self::pitch_to_key(mutated[i - 2].note as f32);
                    let k2 = Self::pitch_to_key(mutated[i - 1].note as f32);
                    self.matrix
                        .transitions_order2
                        .get(&(k1, k2))
                        .and_then(|cands| Self::sample_candidate(cands, self.config.temperature, &mut rng_seed))
                } else {
                    None
                };

                if let Some(gen_event) = candidate {
                    mutated[i].note = gen_event.pitch as f64;
                    if !self.config.pitch_only {
                        mutated[i].velocity = gen_event.velocity;
                        mutated[i].gate = gen_event.gate;
                        mutated[i].probability = gen_event.probability;
                        mutated[i].ratchet = gen_event.ratchet as u32;
                    }
                } else {
                    // Slight variation if no Markov match
                    let delta = (prng_next_f32(&mut rng_seed) * 5.0).round() as f64 - 2.0;
                    mutated[i].note = (mutated[i].note + delta).clamp(36.0, 96.0);
                }

                if let Some(scale) = &self.config.scale_degrees {
                    mutated[i].note = snap_pitch_to_scale(mutated[i].note as f32, scale) as f64;
                }
            }
        }
        mutated
    }

    /// Generate a polyrhythmic `PatternClip` for a target number of measures.
    pub fn generate_polyrhythmic_clip(
        &self,
        name: &str,
        num_measures: usize,
        seed_pitches: &[f32],
        rng_seed: u64,
    ) -> PatternClip {
        let step_beats = self.config.division.step_beats();
        let total_beats = (num_measures as f64) * 4.0;
        let num_steps = (total_beats / step_beats).round() as usize;

        let events = self.generate_sequence(seed_pitches, num_steps, rng_seed);
        let mut clip = PatternClip::new(name, total_beats as f32);

        for ev in events {
            let step = PatternStep {
                note: ev.pitch,
                velocity: ev.velocity,
                gate: ev.gate,
                probability: ev.probability,
                ratchet: ev.ratchet as u32,
                micro_shift: ev.micro_shift as i32,
                pitch_offset: ev.pitch_offset,
                active: ev.active,
                ..Default::default()
            };
            clip.add_step(step);
        }

        clip
    }

    /// Dispatch generated sequence notes into the sequencer timeline.
    pub fn dispatch_to_timeline(
        &self,
        arranger: &mut TimelineArranger,
        track_id: usize,
        start_beat: f64,
        num_steps: usize,
        seed_pitches: &[f32],
        rng_seed: u64,
    ) {
        let step_beats = self.config.division.step_beats();
        let events = self.generate_sequence(seed_pitches, num_steps, rng_seed);

        let notes: Vec<PatternNote> = events
            .into_iter()
            .enumerate()
            .map(|(i, ev)| PatternNote {
                start_beat: (i as f64) * step_beats,
                length_beats: step_beats * (ev.gate as f64).clamp(0.1, 1.0),
                note: ev.pitch as f64,
                velocity: ev.velocity,
                probability: ev.probability,
                ratchet: ev.ratchet as u32,
                micro_shift: ev.micro_shift as i32,
                swing: 0.0,
                pan: 0.0,
                pitch_offset: ev.pitch_offset,
            })
            .collect();

        let total_len = (num_steps as f64) * step_beats;
        arranger.add_clip(Clip {
            start_beat,
            length_beats: total_len,
            track_id: track_id as u64,
            content: ClipContent::Pattern(notes),
        });
    }

    /// Dispatch atomic parameter modulation values into lock-free `ParamBus`.
    /// Safe for non-blocking real-time parameter streaming.
    pub fn dispatch_to_param_bus(
        &self,
        bus: &ParamBus,
        param_pitch_id: ParamId,
        param_velocity_id: ParamId,
        step: &MarkovStepEvent,
    ) {
        bus.set(param_pitch_id, step.pitch);
        bus.set(param_velocity_id, step.velocity);
    }
}

#[inline]
fn prng_next_f32(seed: &mut u64) -> f32 {
    *seed = seed
        .wrapping_mul(6364136223846793005)
        .wrapping_add(1442695040888963407);
    ((*seed >> 33) as f32) / 2147483648.0
}

/// Helper function to snap a pitch to the closest note in a scale.
fn snap_pitch_to_scale(pitch: f32, scale_notes: &[f32]) -> f32 {
    if scale_notes.is_empty() {
        return pitch;
    }

    let mut closest = scale_notes[0];
    let mut min_diff = (pitch - closest).abs();

    for &note in scale_notes.iter().skip(1) {
        let diff = (pitch - note).abs();
        if diff < min_diff {
            min_diff = diff;
            closest = note;
        }
    }

    closest
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_markov_mutator_order2_and_order3_training() {
        let mut mutator = MarkovSequenceMutator::new().with_order(MarkovOrder::Order2);
        let melody = vec![60.0, 62.0, 64.0, 65.0, 67.0, 60.0, 62.0, 64.0, 67.0];

        mutator.train_from_pitches(&melody);

        assert!(!mutator.matrix.transitions_order2.is_empty());
        assert!(!mutator.matrix.transitions_order3.is_empty());

        let key_60_62 = (6000, 6200);
        let cands = mutator.matrix.transitions_order2.get(&key_60_62).unwrap();
        assert!(cands.iter().any(|(ev, _)| (ev.pitch - 64.0).abs() < 0.01));
    }

    #[test]
    fn test_markov_mutator_deterministic_generation() {
        let mut mutator = MarkovSequenceMutator::new().with_temperature(0.5);
        let melody = vec![60.0, 64.0, 67.0, 72.0, 60.0, 64.0, 67.0, 72.0];
        mutator.train_from_pitches(&melody);

        let seq1 = mutator.generate_sequence(&[60.0, 64.0], 16, 0xABCDEF01);
        let seq2 = mutator.generate_sequence(&[60.0, 64.0], 16, 0xABCDEF01);

        assert_eq!(seq1.len(), 16);
        assert_eq!(seq1, seq2, "Markov generation with identical seed must be 100% deterministic");
    }

    #[test]
    fn test_polyrhythmic_division_step_beats() {
        assert_eq!(PolyrhythmicDivision::Quarter.step_beats(), 1.0);
        assert_eq!(PolyrhythmicDivision::Sixteenth.step_beats(), 0.25);
        assert_eq!(PolyrhythmicDivision::Quintuplet16th.step_beats(), 0.2);
        assert_eq!(PolyrhythmicDivision::Septuplet16th.step_beats(), 1.0 / 7.0);
    }

    #[test]
    fn test_markov_timeline_dispatch_and_parambus() {
        let mut mutator = MarkovSequenceMutator::new()
            .with_division(PolyrhythmicDivision::Triplet16th);
        let melody = vec![48.0, 50.0, 52.0, 53.0, 55.0];
        mutator.train_from_pitches(&melody);

        let mut arranger = TimelineArranger::new();
        mutator.dispatch_to_timeline(&mut arranger, 1, 0.0, 12, &[48.0, 50.0], 12345);

        let eval = arranger.evaluate(0.0, 4.0);
        assert_eq!(eval.note_events.len(), 12);

        let mut param_bus = ParamBus::new();
        let p_pitch = param_bus.register(ParamId(0), 0.0);
        let p_vel = param_bus.register(ParamId(1), 0.0);

        let step = MarkovStepEvent::new(55.0, 0.9, 0.8);
        mutator.dispatch_to_param_bus(&param_bus, ParamId(0), ParamId(1), &step);

        assert_eq!(p_pitch.get(), 55.0);
        assert_eq!(p_vel.get(), 0.9);
    }
}
